# Generated by Django 2.0.2 on 2018-04-03 10:22

import company.constants.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20180330_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=company.constants.fields.IntegerRangeField(),
        ),
    ]
