# Generated by Django 2.0.3 on 2018-04-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20180403_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScraptCompnay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Company Name')),
                ('position', models.CharField(max_length=200, verbose_name='Position')),
            ],
        ),
    ]
