# Generated by Django 2.0.2 on 2018-04-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_scraptcompnay'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(default=1, max_length=300, verbose_name='Company Address :'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='Company contact E-mail :'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(default='+880', max_length=15, verbose_name='Phone Number :'),
        ),
    ]
