# Generated by Django 2.0.3 on 2018-04-21 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20180420_2336'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScraptCompnay',
            new_name='ScrapeCompany',
        ),
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.CharField(choices=[('IT', 'IT Company'), ('clothing', 'Clothing'), ('other', 'Other')], max_length=50, verbose_name='Company Type :'),
        ),
    ]
