# Generated by Django 2.0.2 on 2018-04-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20180421_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='images',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
