# Generated by Django 2.0.6 on 2018-07-03 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_company_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScrapeCompany',
        ),
        migrations.RemoveField(
            model_name='company',
            name='images',
        ),
    ]
