# Generated by Django 2.0.6 on 2018-07-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20180703_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.CharField(choices=[('IT', 'IT Company'), ('Clothing', 'Clothing'), ('Other', 'Other')], max_length=50, verbose_name='Company Type :'),
        ),
    ]
