# Generated by Django 2.0.6 on 2018-07-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_auto_20180706_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='company_photos/'),
        ),
    ]
