# Generated by Django 2.0.3 on 2018-03-30 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='Full Name :')),
                ('email', models.EmailField(help_text='username@example.com', max_length=60, unique=True, verbose_name='E-mail :')),
                ('password', models.CharField(max_length=100, verbose_name='Password :')),
                ('zipcode', models.IntegerField(default=0, verbose_name='ZIP Code :')),
                ('dateOfBirth', models.DateField(verbose_name='Date-of-birth : ')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
