# Generated by Django 2.0.2 on 2018-04-20 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180330_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='dateOfBirth',
        ),
        migrations.RemoveField(
            model_name='client',
            name='zip_code',
        ),
    ]
